
CREATE TABLE Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	AccessFailedCount INT NOT NULL,
	ConcurrencyStamp NVARCHAR(max) NULL,
	Dob DATETIME2(7) NOT NULL,
	Email NVARCHAR(256) NULL,
	EmailConfirmed BIT NOT NULL,
	FirstName NVARCHAR(100) NULL,
	Gender NVARCHAR(10) NULL,
	IsCastingProfessional BIT NOT NULL,
	LastName NVARCHAR(100) NULL,
	LockoutEnabled BIT NOT NULL,
	LockoutEnd DATETIMEOFFSET(7) NULL,
	NormalizedEmail NVARCHAR(256) NULL,
	NormalizedUserName NVARCHAR(256) NULL,
	Designation NVARCHAR(150) NULL,
	OrgName NVARCHAR(150) NULL,
	OrgWebsite NVARCHAR(150) NULL,
	PasswordHash NVARCHAR(max) NULL,
	PhoneNumber NVARCHAR(max) NULL,
	PhoneNumberConfirmed BIT NOT NULL,
	SecurityStamp NVARCHAR(max) NULL,
	TwoFactorEnabled BIT NOT NULL DEFAULT(0),
	UserName NVARCHAR(256) NULL,	
	DttmCreted DATETIME NOT NULL DEFAULT(GETUTCDATE()),
	DttmModified DATETIME NOT NULL DEFAULT(GETUTCDATE())
	)

GO

CREATE TABLE UserAddresses (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	AccessFailedCount INT NOT NULL,
	AppOrHouseName NVARCHAR(150) NOT NULL,
	CityOrTown NVARCHAR(100) NOT NULL,
	Country NVARCHAR(50) NOT NULL,
	Flat NVARCHAR(50) NOT NULL,
	LandMark NVARCHAR(200) NOT NULL,
	LineOne NVARCHAR(200) NOT NULL,
	LineTwo NVARCHAR(200) NULL,
	StateOrProvince NVARCHAR(100) NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	ZipOrPostalCode NVARCHAR(10) NOT NULL,	
	DttmCreted DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
	DttmModified DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
	FOREIGN KEY (UserId) REFERENCES Users(Id)
	)
