
CREATE TABLE Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	AccessFailedCount INT NOT NULL,
	ConcurrencyStamp NVARCHAR(max) NULL,
	Email NVARCHAR(256) NULL,
	EmailConfirmed BIT NOT NULL,
	FirstName NVARCHAR(100) NULL,
	Gender NVARCHAR(10) NULL,
	IsCastingProfessional BIT NOT NULL,
	LastName NVARCHAR(100) NULL,
	LockoutEnabled BIT NOT NULL,
	LockoutEnd DATETIMEOFFSET(7) NULL,
	NormalizedEmail NVARCHAR(256) NULL,
	NormalizedUserName NVARCHAR(256) NULL,
	Designation NVARCHAR(150) NULL,
	OrgName NVARCHAR(150) NULL,
	OrgWebsite NVARCHAR(150) NULL,
	PasswordHash NVARCHAR(max) NULL,
	PhoneNumber NVARCHAR(max) NULL,
	PhoneNumberConfirmed BIT NOT NULL,
	SecurityStamp NVARCHAR(max) NULL,
	TwoFactorEnabled BIT NOT NULL DEFAULT(0),
	UserName NVARCHAR(256) NULL,	
	DttmCreated DATETIME NOT NULL DEFAULT(GETUTCDATE()),
	DttmModified DATETIME NOT NULL DEFAULT(GETUTCDATE())
	)

GO

CREATE TABLE UserAddress (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	UserId UNIQUEIDENTIFIER NOT NULL,	
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	AccessFailedCount INT NOT NULL,
	AppOrHouseName NVARCHAR(150) NOT NULL,
	CityOrTown NVARCHAR(100) NOT NULL,
	Country NVARCHAR(50) NOT NULL,
	Flat NVARCHAR(50) NOT NULL,
	LandMark NVARCHAR(200) NOT NULL,
	LineOne NVARCHAR(200) NOT NULL,
	LineTwo NVARCHAR(200) NULL,
	StateOrProvince NVARCHAR(100) NOT NULL,
	ZipOrPostalCode NVARCHAR(10) NOT NULL,	
	DttmCreated DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
	DttmModified DATETIME2(7) NOT NULL DEFAULT(GETUTCDATE()),
	FOREIGN KEY (UserId) REFERENCES Users(Id)
	)

	GO

CREATE TABLE UserDetail (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),	
	UserId UNIQUEIDENTIFIER NOT NULL,	
	About NVARCHAR(1500) NULL,
	Age INT NOT NULL,
	BloodGroup INT NOT NULL,
	DateOfBirth DATETIME2(7) NOT NULL,
	Disability NVARCHAR(max) NULL,
	HealthInfo NVARCHAR(200) NULL,
	MaritalStatus INT NOT NULL,
	MotherTongue NVARCHAR(100) NULL,
	Nickname NVARCHAR(200) NULL,
	ProfileAddress NVARCHAR(200) NULL,
	Religion NVARCHAR(100) NULL,
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	DttmCreated DATETIME2(7) NOT NULL,
	DttmModified DATETIME2(7) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(Id)
	)
GO

CREATE TABLE PhysicalAppearance (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),	
	UserId UNIQUEIDENTIFIER NOT NULL,
	BodyType INT NOT NULL,
	Chest INT NOT NULL,
	EyeColor INT NOT NULL,
	HairColor INT NOT NULL,
	HairLength INT NOT NULL,
	HairType INT NOT NULL,
	SkinColor INT NOT NULL,
	Height INT NOT NULL,
	Weight INT NOT NULL,
	West INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	DttmCreated DATETIME2(7) NOT NULL,
	DttmModified DATETIME2(7) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(Id)
	)
GO

CREATE TABLE Accents (
	Id BIGINT PRIMARY KEY NOT NULL IDENTITY(1, 1),		
	Accent NVARCHAR(150) NULL,
	STATUS INT NOT NULL,	
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0)
	)
GO

CREATE TABLE UserAsent (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),	
	UserId UNIQUEIDENTIFIER NOT NULL,	
	AccentsId BIGINT NOT NULL,
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	DttmCreated DATETIME2(7) NOT NULL,
	DttmModified DATETIME2(7) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (AccentsId) REFERENCES Accents(Id)
	)
GO

CREATE TABLE Languages (
	Id BIGINT PRIMARY KEY NOT NULL IDENTITY(1, 1),	
	Code NVARCHAR(50) NULL,
	Language NVARCHAR(100) NULL,
	Status INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0)
	)
GO

CREATE TABLE UserLanguage (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	UserId UNIQUEIDENTIFIER NOT NULL,
	LanguagesId BIGINT NOT NULL,
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	DttmCreated DATETIME2(7) NOT NULL,
	DttmModified DATETIME2(7) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (LanguagesId) REFERENCES Languages(Id)
	)
GO
CREATE TABLE SocialAddress (
	Id BIGINT PRIMARY KEY NOT NULL IDENTITY(1, 1),	
	HelpUrl NVARCHAR(200) NULL,
	IconClass NVARCHAR(100) NULL,
	PostLabel NVARCHAR(200) NULL,
	PostUrl NVARCHAR(200) NULL,
	PreUrl NVARCHAR(200) NULL,
	SocialName NVARCHAR(200) NULL,
	Status INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0)
	)
GO

CREATE TABLE UserSocialAddress (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
	UserId UNIQUEIDENTIFIER NOT NULL,
	SocialAddressId BIGINT NOT NULL,
	SocialUserName NVARCHAR(200) NULL,
	STATUS INT NOT NULL,
	IsActive BIT NOT NULL DEFAULT(0),
	IsDeleted BIT NOT NULL DEFAULT(0),
	DttmCreated DATETIME2(7) NOT NULL,
	DttmModified DATETIME2(7) NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (SocialAddressId) REFERENCES SocialAddress(Id)
	)
GO